"""tg_user

Revision ID: 9cc3f9074f9a
Revises: 
Create Date: 2021-02-27 11:35:30.282009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9cc3f9074f9a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('telegram_user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exchange_data', sa.Text(), nullable=True),
    sa.Column('exchange_data_saved_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_telegram_user_exchange_data_saved_at'), 'telegram_user', ['exchange_data_saved_at'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_telegram_user_exchange_data_saved_at'), table_name='telegram_user')
    op.drop_table('telegram_user')
    # ### end Alembic commands ###
